# Generated by Django 4.2.9 on 2024-08-12 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=30)),
                ('description', models.TextField(blank=True, default='', max_length=1000)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7)),
                ('brand', models.CharField(blank=True, default='', max_length=30)),
                ('category', models.CharField(choices=[('Clothes', 'Clothes'), ('Electronics', 'Electronics'), ('Furniture', 'Furniture'), ('Beauty', 'Beauty')], max_length=30)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=3)),
                ('stock', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
